services:
  - type: web
    name: gpt-drive-proxy
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn proxy_app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
